### ISSUE TITLE
Should be closing response..

### ISSUE THREAD

**Issue by nicpottier** [dcelasun/librato#1]
See https://github.com/golang/go/issues/4049

This is likely leaking the response right now.

Just need a `defer resp.Body.Close()` after the `Do`.

**Comment by nicpottier** [comment]
Actually glancing at: 
  https://stackoverflow.com/questions/17948827/reusing-http-connections-in-golang

Looks like we really need to read the response fully for the connection to be returned.

So need:
```
res, _ := client.Do(req)
io.Copy(ioutil.Discard, res.Body)
res.Body.Close()
```

**Comment by dcelasun** [comment]
Fixed, thanks!
